### POST /signup - Sign Up with Email and Password
POST  http://172.20.10.3:3000/signup
Content-Type: application/json

{
  "email": "test123@gmail.com",
  "password": "test123"
}

#### POST /post_email - Post Email
POST http://10.100.102.25:3000/post_email
Content-Type: application/json

{
    "email": "bar31616@gmail.com"
}


### POST /post_password - Post Password
POST  http://10.100.102.25:3000/post_password
Content-Type: application/json

{
  "password": "test123"
}


### POST /login - Post login
POST  http://172.20.10.3:3000/login
Content-Type: application/json

{
  "email": "Bar31616@gmail.com",
  "password": "Bar1234"
}


### POST /resetPass - Post login
POST  http://172.20.10.3:3000/resetPass
Content-Type: application/json

{
  "email": "idobn98@gmail.com"
}


### Fetch Place Details
GET http://192.168.33.29:3000/place-details/ChIJvY4MLQmjAhUR1sOGnGeGoj0
Content-Type: application/json

{
  "place_id": "ChIJvY4MLQmjAhUR1sOGnGeGoj0"
}

### Fetch Place Details
POST http://172.20.10.3:3000/addDetails
Content-Type: application/json

{
  "uid": "vZ24Kn8WLoVesI2c796ptTa5R2v2",
  "name": "Bar Cohen",
  "birthday": "1996-03-14",
  "gender": "Male"
}

